### PR TITLE
[WIP] Update existing images and add Ubuntu 20.04

### LINKED ISSUE #4: Add Ubuntu 20.04
Github [has added Ubuntu 20.04](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners) to their available virtual environments. Time to add it here!

🥂 🎉 Cheers!

### PR DESCRIPTION
**Pull request by lumaxis**
Closes #4

I wanted to update the images with the latest state from https://github.com/actions/virtual-environments and tried to deduce the necessary changes from the current versions of the `ubuntu*.json` files here.

### CODE REVIEW

**Comment by lumaxis** [comment]
My test build of the images is still running, so don't yet know if they actually work – hence the `[WIP]` tag 😬

**Comment by cplee** [comment]
let me know what the results show @lumaxis 🤞

**Comment by lumaxis** [comment]
I think my Docker disk ran out of disk space 😆 Trying again!

**Comment by cplee** [comment]
@lumaxis fwiw, I did my building of images on an AWS Cloud9 instance

**Comment by alxs** [comment]
@lumaxis did you manage to get this running? Ubuntu 20.04 is currently being [rolled out](https://github.com/actions/virtual-environments/issues/1816) as the default for ubuntu-latest workflows.

**Comment by lumaxis** [comment]
Unfortunately I never did and currently don't really have the capacity to work on this further 😕 
If anyone wants to build on top of this work and continue my quest, please feel free 🙏🏼

**Comment by catthehacker** [comment]
you can try `catthehacker/ubuntu:full-20.04` which is only few months old

**Comment by shuhaowu** [comment]
Where's that image built from? I can't find the source?

**Comment by catthehacker** [comment]
It was built from Dockerfile I wrote based on the `ubuntu2004.json` Packer template and scripts from https://github.com/actions/virtual-environments but the source Dockerfile is not available anymore

**Comment by gene1wood** [comment]
Given that the main act README ( https://github.com/nektos/act#runners ) suggests users use @catthehacker 's hosted docker images as of ~~nektos/act#463~~ ( whoops, actually nektos/act#523 ) , and those include an image for Ubuntu 20.04 ( `ghcr.io/catthehacker/ubuntu:act-20.04` ) which comes from https://github.com/catthehacker/docker_images should this PR be closed?

Should @catthehacker PR in his solution to this into this `nektos` repo?

**Comment by lumaxis** [comment]
> should this PR be closed?

Yes, I think so.

**Comment by catthehacker** [comment]
> Should @catthehacker PR in his solution to this into this `nektos` repo?

If you mean medium images I can just transfer the repo and if desirable, images could be published on Nektos Docker Hub/GitHub Container Registry.
Also `act-20.04` and other versions/variants don't include full set of tools that GitHub runner does (they are meant to be most compatible with minimum required tools installed), `full-latest`/`full-20.04`/`full-18.04` should be most "tool-complete" since it's built from the Packer template (https://github.com/catthehacker/virtual-environments-fork/tree/master/images/linux).
I'm also planning to do `slim`/`lite` version that has most but not all tools/multiple versions of tools (like [`act-environments-ubuntu:18.04-lite`](https://hub.docker.com/layers/nektos/act-environments-ubuntu/18.04-lite/images/sha256-4d991875312e2ad084ff5350aa193e8a7dbdc4c144476d48df6a69e1e3404427?context=explore) that is sort of a middle ground between massive image and small images, but haven't had the time yet due to health issues.

> [nektos/act#463](https://github.com/nektos/act/pull/463)

I think you meant https://github.com/nektos/act/pull/523 :)

**Pull request closed without merging**
